Controllers/CircuitsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using tpeapp.Context;
using tpeapp.Models;

namespace tpeapp.Controllers
{
    public class CircuitsController : Controller
    {
        private readonly AppDbContext _context;

        public CircuitsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Circuits
        public async Task<IActionResult> Index()
        {
              return View(await _context.Circuits.ToListAsync());
        }

        // GET: Circuits/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Circuits == null)
            {
                return NotFound();
            }

            var circuitsModel = await _context.Circuits
                .FirstOrDefaultAsync(m => m.CircuitId == id);
            if (circuitsModel == null)
            {
                return NotFound();
            }

            return View(circuitsModel);
        }

        // GET: Circuits/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Circuits/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CircuitId,CircuitName")] CircuitsModel circuitsModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(circuitsModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(circuitsModel);
        }

        // GET: Circuits/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Circuits == null)
            {
                return NotFound();
            }

            var circuitsModel = await _context.Circuits.FindAsync(id);
            if (circuitsModel == null)
            {
                return NotFound();
            }
            return View(circuitsModel);
        }

        // POST: Circuits/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CircuitId,CircuitName")] CircuitsModel circuitsModel)
        {
            if (id != circuitsModel.CircuitId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(circuitsModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CircuitsModelExists(circuitsModel.CircuitId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(circuitsModel);
        }

        // GET: Circuits/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Circuits == null)
            {
                return NotFound();
            }

            var circuitsModel = await _context.Circuits
                .FirstOrDefaultAsync(m => m.CircuitId == id);
            if (circuitsModel == null)
            {
                return NotFound();
            }

            return View(circuitsModel);
        }

        // POST: Circuits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Circuits == null)
            {
                return Problem("Entity set 'AppDbContext.Circuits'  is null.");
            }
            var circuitsModel = await _context.Circuits.FindAsync(id);
            if (circuitsModel != null)
            {
                _context.Circuits.Remove(circuitsModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CircuitsModelExists(int id)
        {
          return _context.Circuits.Any(e => e.CircuitId == id);
        }
    }
}

Controllers/PointsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using tpeapp.Context;
using tpeapp.Models;

namespace tpeapp.Controllers
{
    public class PointsController : Controller
    {
        private readonly AppDbContext _context;

        public PointsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Points
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Points.Include(p => p.Schedules);
            return View(await appDbContext.ToListAsync());
        }

        // GET: Points/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Points == null)
            {
                return NotFound();
            }

            var pointsModel = await _context.Points
                .Include(p => p.Schedules)
                .FirstOrDefaultAsync(m => m.PointId == id);
            if (pointsModel == null)
            {
                return NotFound();
            }

            return View(pointsModel);
        }

        // GET: Points/Create
        public IActionResult Create()
        {
            ViewData["SchedulesId"] = new SelectList(_context.Schedules, "SchedulesId", "SchedulesId");
            return View();
        }

        // POST: Points/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PointId,PointName,SchedulesId")] PointsModel pointsModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pointsModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SchedulesId"] = new SelectList(_context.Schedules, "SchedulesId", "SchedulesId", pointsModel.SchedulesId);
            return View(pointsModel);
        }

        // GET: Points/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Points == null)
            {
                return NotFound();
            }

            var pointsModel = await _context.Points.FindAsync(id);
            if (pointsModel == null)
            {
                return NotFound();
            }
            ViewData["SchedulesId"] = new SelectList(_context.Schedules, "SchedulesId", "SchedulesId", pointsModel.SchedulesId);
            return View(pointsModel);
        }

        // POST: Points/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PointId,PointName,SchedulesId")] PointsModel pointsModel)
        {
            if (id != pointsModel.PointId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pointsModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PointsModelExists(pointsModel.PointId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SchedulesId"] = new SelectList(_context.Schedules, "SchedulesId", "SchedulesId", pointsModel.SchedulesId);
            return View(pointsModel);
        }

        // GET: Points/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Points == null)
            {
                return NotFound();
            }

            var pointsModel = await _context.Points
                .Include(p => p.Schedules)
                .FirstOrDefaultAsync(m => m.PointId == id);
            if (pointsModel == null)
            {
                return NotFound();
            }

            return View(pointsModel);
        }

        // POST: Points/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Points == null)
            {
                return Problem("Entity set 'AppDbContext.Points'  is null.");
            }
            var pointsModel = await _context.Points.FindAsync(id);
            if (pointsModel != null)
            {
                _context.Points.Remove(pointsModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PointsModelExists(int id)
        {
          return _context.Points.Any(e => e.PointId == id);
        }
    }
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using tpeapp.Context;
using tpeapp.Models;

namespace tpeapp.Controllers
{
    public class UsersController : Controller
    {
        private readonly AppDbContext _context;

        public UsersController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
              return View(await _context.Users.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var usersModel = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (usersModel == null)
            {
                return NotFound();
            }

            return View(usersModel);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,UserName,IsMan,IsWoman,UserBirthDate,UserBaptismDate,UserPhone,UserEmail,IsPublisher,IsPioneer,IsMinisterialServant,IsElder,IsPioneerAndMinisterialServant,IsPioneerAndElder,CongregationId")] UsersModel usersModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(usersModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(usersModel);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var usersModel = await _context.Users.FindAsync(id);
            if (usersModel == null)
            {
                return NotFound();
            }
            return View(usersModel);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,UserName,IsMan,IsWoman,UserBirthDate,UserBaptismDate,UserPhone,UserEmail,IsPublisher,IsPioneer,IsMinisterialServant,IsElder,IsPioneerAndMinisterialServant,IsPioneerAndElder,CongregationId")] UsersModel usersModel)
        {
            if (id != usersModel.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usersModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsersModelExists(usersModel.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usersModel);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var usersModel = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (usersModel == null)
            {
                return NotFound();
            }

            return View(usersModel);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Users == null)
            {
                return Problem("Entity set 'AppDbContext.Users'  is null.");
            }
            var usersModel = await _context.Users.FindAsync(id);
            if (usersModel != null)
            {
                _context.Users.Remove(usersModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsersModelExists(int id)
        {
          return _context.Users.Any(e => e.UserId == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]TPE App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/tpeapp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                &nbsp;
                &nbsp;
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TPE</a>
                &nbsp;
                &nbsp;
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">

                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                            Gerenciar Usuários
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            <a class="dropdown-item" asp-area="" asp-controller="Users" asp-action="Index">Usuários</a>
                            <a class="dropdown-item" asp-area="" asp-controller="UsersSchedules" asp-action="Index"> Horários e Dias</a>
                        </div>
                    </div>
                    &nbsp;
                    &nbsp;
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                            Gerenciar Pontos e Horários
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            <a class="dropdown-item" asp-area="" asp-controller="Schedules" asp-action="Index"> Horários e Dias</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Points" asp-action="Index"> Pontos</a>
                        </div>
                    </div>

                     @* <a class="nav-link text-light" asp-area="" asp-controller="Users" asp-action="Index">Usuários</a> *@

                  

                    <a class="nav-link text-light" asp-area="" asp-controller="Congregations" asp-action="Index">Congregações</a>
                    <a class="nav-link text-light" asp-area="" asp-controller="Circuits" asp-action="Index">Circuitos</a>
                    @* <a class="nav-link text-light" asp-area="" asp-controller="Points" asp-action="Index">Pontos</a> *@

                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="PointsCarouselView">PontosCarousel</a>


                </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Testemunho Público Especial - Mauá
        </div>
    </footer>i

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>